### ISSUE TITLE
努比亚Z11无法进入比赛

### ISSUE THREAD

**Issue by nullmax** [zlsq/A9#10]
* 脚本启动后按流程进入EURO12关卡，然后第一辆选的车竟然是911！！！，而且选好车后没法进入比赛，点到了欣赏车的界面。
* 我是帮群友提的，没法去测试他的设备。我让他自己修改下goldenPoint的值，但是依然无法解决问题。不知道您那里是否能测试该机型呢。

**Comment by Dr-Omega9834** [comment]
请问设备型号和分辨率呢

**Comment by Dr-Omega9834** [comment]
有空之后会加QQ
