### ISSUE TITLE
建议写明语言

### ISSUE THREAD

**Issue by prometheusjoe** [zlsq/A9#11]
不知道是不是坐标的问题，我发现用英文版就报错好几次，但是用中文就啥事都没有

**Comment by zlsq** [comment]
可能在取坐标之后,判断坐标按钮的颜色出现了问题, 有时我需要判断按钮的颜色, 但是这个颜色被文字给覆盖了(之前存在过这种情况), 导致判断颜色错误. 还请问你是用的哪个脚本在哪个环节出错了, 我重新取点看看

**Comment by prometheusjoe** [comment]
> 可能在取坐标之后,判断坐标按钮的颜色出现了问题, 有时我需要判断按钮的颜色, 但是这个颜色被文字给覆盖了(之前存在过这种情况), 导致判断颜色错误. 还请问你是用的哪个脚本在哪个环节出错了, 我重新取点看看

经常出现在主屏幕运行时发生错误，应该是开始按钮的坐标问题

**Comment by zlsq** [comment]
嗯, 我发现问题了, 中文的确和英文 框的布局都有不同, 我取点的时候会注意的, 对于2160和1080的我都改了位置了
