### ISSUE TITLE
建议为刚通玩家改一个刷金币独立脚本

### ISSUE THREAD

**Issue by hackjakcn** [zlsq/A9#13]
1920*1080分辨率。
我的euroshow赛季刚通十二关，因此刷金币完成一局返回默认在13关，可直接点12关继续刷而无需拉屏幕。
我将你的刷金币脚本修改了64行block12坐标x675.y930。362行删除swipescreen指令即可正常运行。供参考。另资助三十文，从你这学了不少

**Comment by zlsq** [comment]
你好, 首先感谢您使用了我的脚本并资助, 说实话我平常也很少写js, 这个脚本是边看mdn的js教程边写得... 所以说从我这学到不少实属谦虚了,2333..
你说的给未通关得适配下, 我觉得可能过于麻烦. 不准备做这个, 因为euro赛季是一个比较好过得赛季, 可用车辆多, 从第一关到解锁最后一关用不了多长时间.最近工作比较忙, 脚本更新的少, 闲下来之后我会考虑增加更多的功能, 请持续关注本repo
