### ISSUE TITLE
newcar unleash翻车提醒

### ISSUE THREAD

**Issue by hackjakcn** [zlsq/A9#14]
新更新的新车发布脚本在本次j50活动中因右划定时器设置500，较高性能车因右划不及时容易终点前上板翻车拿不到代币。经测试将235行右划代码延迟调到300即可避免翻车

**Comment by zlsq** [comment]
ok, 500是我随机写得一个时间, 上赛季bc时一直往右滑动快点, 这赛季我没改.....
