### ISSUE TITLE
大佬  一轮结束一直点右下角

### ISSUE THREAD

**Issue by frebrd** [zlsq/A9#15]
是杯赛脚本

**Comment by frebrd** [comment]
能不能去掉代币结算啊

**Comment by frebrd** [comment]
解决了  cutdown的坐标好像颠倒了

**Comment by zlsq** [comment]
嗯, 我发现根据语言不同 cutdown的坐标也似乎不同, 我正在解决这些问题, 你如果自己解决了 也可以pull request
